# Generated by Django 4.1.7 on 2023-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.BigIntegerField(verbose_name='Id пользователя')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(verbose_name='Фамилия')),
                ('tg_tag', models.TextField(verbose_name='Тег телеграм')),
                ('score', models.IntegerField(verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='PlayerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.BigIntegerField(verbose_name='Player')),
                ('place', models.TextField(verbose_name='Корпус')),
                ('stage', models.IntegerField(verbose_name='Этап')),
                ('questions', models.CharField(max_length=100, verbose_name='Tasks')),
                ('qr_codes', models.CharField(max_length=100, verbose_name='QrCodes')),
            ],
            options={
                'verbose_name': 'Вопросы для участников',
            },
        ),
        migrations.CreateModel(
            name='QrCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер кода')),
                ('pokr', models.TextField(verbose_name='Описание Покра')),
                ('miem', models.TextField(verbose_name='Описание МИЭМ')),
                ('vsb', models.TextField(verbose_name='Описание ВШБ')),
                ('bas', models.TextField(verbose_name='Описание Басмач')),
                ('mo', models.TextField(verbose_name='Описание Международные отношения')),
                ('code', models.CharField(max_length=30, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер вопроса')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=30, verbose_name='Ответ')),
            ],
        ),
    ]
