# Generated by Django 4.1.7 on 2023-03-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_player_time1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time1',
            field=models.TimeField(),
        ),
    ]
